@startuml Contexto
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

' Layout e legendas
LAYOUT_LEFT_RIGHT()
LAYOUT_WITH_LEGEND()

' Elementos do diagrama de contexto
Person(jose, "José", "Analista de Dados")
System_Boundary(Cloud, "Azure Databricks") {
    System(databricks, "Databricks", "Plataforma de Análise de Dados")
    System_Ext(data_sources, "Fontes de Dados", "CSV de Inadimplência e Indicadores Econômicos")
    System_Ext(power_bi, "Power BI", "Ferramenta de Visualização de Dados")
    System_Ext(github, "GitHub", "Repositório de Código")
    System_Ext(azure, "Azure", "Plataforma de Nuvem")
}

Rel(jose, github, "Versiona e Armazena Código")
Rel(github, databricks, "Integra com")

Rel(jose, databricks, "Desenvolve e Executa Pipelines de ETL")
Rel(databricks, data_sources, "Carrega dados de")
Rel(databricks, power_bi, "Exporta dados para")
Rel(databricks, azure, "Hospeda e Processa Dados")
Rel(jose, power_bi, "Cria Dashboards e Visualizações")

footer
    MVP - Engenharia de dados - PUC RIO - 2024 - PlantUML version %version() - Diagrama v1.0 - @2024 - José Matos
endfooter
@enduml